module.exports = {
  'WIN_UPDATECONFIG': 'WIN_UPDATECONFIG',
  'WIN_UPDATECONFIG_REPLY': 'WIN_UPDATECONFIG_REPLY',
  'WIN_SEND_GLOBALCONFIG': 'WIN_SEND_GLOBALCONFIG',
  'WIN_COPY_TEMPLATE': 'WIN_COPY_TEMPLATE',
  'WIN_COPY_TEMPLATE_REPLY': 'WIN_COPY_TEMPLATE_REPLY'
}